### ISSUE TITLE
Can't scroll on input-numeric plugin page

### ISSUE THREAD

**Issue by gbonline** [EddyVerbruggen/nativescript-pluginshowcase#23]
Hi, I like your demo app for the most useful plugins for Nativescript.
But as I write in the object, on my phone 5.5" with Android 8.1, 
when in the Tab Numeric, for the Input plugins, appear the onscreen keyboard, 
the keyboard is over the fields and the form don't scroll so I don't know which field I'm filling
Bye

**Comment by EddyVerbruggen** [comment]
Yeah that page is not too interesting for Android anyway as the related plugin enhances the keyboard for iOS only. The reason it's shown on Android as well is because I'd like to show it gracefully falls back to the normal numeric keyboard on Android.

That being said, I can probably fix this by tweaking the AndroidManifest.xml file.

**Comment by EddyVerbruggen** [comment]
Yep, changing a property in AndroidManifest.xml did the trick. See the related commit.
